#!/bin/bash

set -eu

version=$(curl -s https://mattermost.com/download/ | grep "Latest Release:" | head -n1 | egrep -o '[0-9]+\.[0-9]+\.[0-9]+')

: ${version:?failed to extract version from upstream page}

echo $version > version/number

echo "Version: $version"
