#!/bin/bash

set -e

version=$(cat version/number)

echo "Mattermost v${version} was released upstream" > notifications/message

mkdir -p gh/artifacts
echo "v${version}" > gh/name
echo "v${version}" > gh/tag
echo "See https://docs.mattermost.com/administration/changelog.html" > gh/notes.md

cd gh/artifacts
curl https://releases.mattermost.com/mattermost-load-test/mattermost-load-test.tar.gz -o mattermost-load-test-${version}.tar.gz
curl https://releases.mattermost.com/${version}/mattermost-team-${version}-linux-amd64.tar.gz -O
curl https://releases.mattermost.com/${version}/mattermost-${version}-linux-amd64.tar.gz -O
cd ..

ls -al **/*
