#!/bin/bash

cp version/number blobs/version
cd blobs

wget https://releases.mattermost.com/${version}/mattermost-team-${version}-linux-amd64.tar.gz
wget https://releases.mattermost.com/${version}/mattermost-${version}-linux-amd64.tar.gz
wget https://releases.mattermost.com/mattermost-load-test/mattermost-load-test.tar.gz
mv mattermost-load-test.tar.gz mattermost-load-test-${version}.tar.gz
