---
meta:
  name:    mattermost-releases
  target:  sw
  url:     https://ci.starkandwayne.com

  github:
    owner:  starkandwayne
    repo:   (( grab meta.pipeline ))
    branch: master
    private_key:  (( vault "secret/pipelines/shared/github:private_key" ))
    access_token: (( vault "secret/pipelines/shared/github:access_token" ))

  slack:
    webhook:  (( vault "secret/pipelines/mattermost-boshrelease/slack:webhook" ))
